// Builds the cross-language test vector: a state, its EIP-712 digest and real signatures made with viem.
// `bun packages/protocol/scripts/vault-vector.js` rewrites contracts/test/vectors/state.json; the protocol
// test checks the file is current and the Foundry test feeds it to the real contract.
import { writeFileSync } from 'node:fs';
import { getTypesForEIP712Domain, hashDomain, hashTypedData, keccak256, toHex } from 'viem';
import { privateKeyToAccount } from 'viem/accounts';
import { STATE_TYPES, stateTypedData } from '../src/vault.js';

/** EIP-712 encodeType for the State struct (it has no nested structs). */
export const STATE_TYPE_STRING = `State(${STATE_TYPES.State.map((f) => `${f.type} ${f.name}`).join(',')})`;

export const VECTOR_PATH = new URL('../../../contracts/test/vectors/state.json', import.meta.url);

// Throwaway keys derived from names. They only exist to make this test vector; never fund them.
const account = (name) => privateKeyToAccount(keccak256(toHex(`pgg-test-vector:${name}`)));

export async function buildVector() {
  const chainId = 31337;
  const vault = '0x00000000000000000000000000000000000dead1';
  const arbiter = account('arbiter');
  const wallets = ['player-a', 'player-b', 'player-c']
    .map((name) => ({
      name,
      wallet: account(`wallet:${name}`),
      session: account(`session:${name}`),
    }))
    .sort((a, b) => (BigInt(a.wallet.address) < BigInt(b.wallet.address) ? -1 : 1));

  const state = {
    tableId: keccak256(toHex('pgg-vector-table')),
    nonce: 7,
    isFinal: true,
    players: wallets.map((w) => w.wallet.address),
    // three players deposited 1,000 each (6 decimals); 40 went to rake; players 0 and 2 stay on
    balances: [1500_000000, 900_000000, 560_000000],
    keep: [true, false, true],
    rake: 40_000000,
    volume: 4000_000000,
  };

  const typed = stateTypedData(state, { chainId, verifyingContract: vault });
  const digest = hashTypedData(typed);
  const domainSeparator = hashDomain({
    domain: typed.domain,
    types: { EIP712Domain: getTypesForEIP712Domain({ domain: typed.domain }) },
  });

  return {
    note: 'Generated by packages/protocol/scripts/vault-vector.js. Test keys only.',
    chainId,
    vault,
    arbiter: arbiter.address,
    players: state.players,
    sessionKeys: wallets.map((w) => w.session.address),
    state: { ...state, tableId: state.tableId },
    stateTypehash: keccak256(toHex(STATE_TYPE_STRING)),
    domainSeparator,
    digest,
    signatures: {
      arbiter: await arbiter.signTypedData(typed),
      players: await Promise.all(wallets.map((w) => w.session.signTypedData(typed))),
    },
  };
}

if (import.meta.main) {
  const vector = await buildVector();
  writeFileSync(VECTOR_PATH, `${JSON.stringify(vector, null, 2)}\n`);
  console.log('wrote', VECTOR_PATH.pathname);
}
